using System.Text.Json.Nodes;
using AutonomousResearchAgent.Application.Papers;
using AutonomousResearchAgent.Application.Summaries;
using Microsoft.Extensions.Logging;

namespace AutonomousResearchAgent.Infrastructure.Services;

public sealed class PlaceholderSummarizationService(ILogger<PlaceholderSummarizationService> logger) : ISummarizationService
{
    public Task<JsonNode?> GenerateSummaryAsync(PaperDetail paper, string modelName, string promptVersion, CancellationToken cancellationToken)
    {
        logger.LogDebug("Generating placeholder summary for paper {PaperId}", paper.Id);

        JsonNode result = new JsonObject
        {
            ["shortSummary"] = $"Placeholder summary for '{paper.Title}'.",
            ["longSummary"] = paper.Abstract ?? "No abstract is currently stored.",
            ["keyFindings"] = new JsonArray(JsonValue.Create("Generated by placeholder summarization service.")),
            ["methods"] = new JsonArray(),
            ["limitations"] = new JsonArray(JsonValue.Create("Replace with a real summarization provider.")),
            ["tags"] = new JsonArray(JsonValue.Create(modelName), JsonValue.Create(promptVersion)),
            ["confidence"] = 0.2,
            ["extractedClaims"] = new JsonArray()
        };

        return Task.FromResult<JsonNode?>(result);
    }
}
